#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;
use WPINT\Core\Foundation\Application;

$path = dirname(__DIR__, 3). '/wp-load.php';
if(file_exists($path)){
    require_once dirname(__DIR__, 3). '/wp-load.php';
}

define('WPINT_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = app();


$status = $app->handleCommand(new ArgvInput);

exit($status);